Changes for v0.20.0 release
conda-forge/iris-grib-feedstock pull request #38
Opened 2024-08-30 15:36 UTC by pp-mo

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2024-08-30 15:36 UTC, pp-mo commented
@conda-forge-admin, please rerender

2024-09-02 08:28 UTC, trexfeathers commented on recipe/meta.yaml
> +{% set name = "iris_grib" %}
Well spotted, I had forgotten about this since conda-forge/iris-feedstock#111

2024-09-02 08:32 UTC, trexfeathers requested changes

2024-09-02 08:32 UTC, trexfeathers commented on recipe/meta.yaml
> +    - setuptools-scm >=7
```suggestion
    - setuptools-scm >=8
```

https://github.com/SciTools/iris-grib/blob/1eec6a6af05d8d40080e9669a0cedc693a4809fe/requirements/py310.yml#L11

2024-09-02 08:39 UTC, trexfeathers approved these changes

2024-09-02 08:39 UTC, merged